language: python
python:
  - "3.6"
cache: pip
install:
  - pip install requests
script:
  - python update_readme.py
after_success:
   - .travis/push.sh
env:
  gobal:
   - secure: "cVUndKyJXJzeaTod2Slh6EmPj25ssX8B/3D76/BbDEZDnrw2QtWUmzRC5DRRtRVthrj19m+VP5H5VPbpftkb6bnJ9LO+fe/WGWyI7mZCbgnwRK0ePOqReFo6FTv0PwhK7m28b+NiG0Pi9S9FKMzZOhziCBFaCuU+VM0B0nqEQKqaD7YRrOUR3fH1vSExjYDiwNePGWzyUiEeEwY8+Wd2K9dkjlr2qMT5Njzlz8rKue+Wh74ri3XOPAEqknynkBrz8pr7YiMd+ZUCgjncrKS9PLvX2vlrbXzcnQI6IJzwTkGt22rgKWSTHTsaZNRej2pDQ6y7MWXcQQmu5g8ZAvEJdBfu9CEKE+uhzOfjeBvTFtpUrZm62XtJEeESgT7LfAIdPISizcjKiNeeyI8ul2lBkKZUUVdJTxU2ihvYlfNEFXJYMvXDulVqvziaEhIlHbZtKqYLftFKx457Yqf10QLQYmpOc6t0D3JNPC+xUoqpF8bh6cC1CEYOZdTAnMPXcXiZ6ibWGyern6N1JVjcyTBGzd5o0clqlI8qcfl1TDEa4n+daJ3L7vpcTExx/n2EXznk3arAsCNUdRh9ZOkHrhIkD7LA/r81SQ7Aorg4GvbbcgQD3StkT21aoHuUpz2sa21SFmyWk8yY3XtQFHqz4TsYg/4TPsJXkuUyaJsKWmy6Cuc="

