# 389. Find the Difference

# Given two strings s and t which consist of only lowercase letters.

# String t is generated by random shuffling string s and then add one more
# letter at a random position.

# Input:
# s = "abcd"
# t = "abcde"

# Output:
# e


# Explanation:
# 'e' is the letter that was added.
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        hash_table = {}
        for c in t:
            if hash_table.get(c) is not None:
                hash_table[c] += 1
            else:
                hash_table[c] = 1
        for c in s:
            hash_table[c] -= 1

        for k, v in hash_table.items():
            if v != 0:
                return k


print(Solution().findTheDifference("aaa", "aaac"))
